# Generated by Django 5.2.8 on 2025-11-25 16:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('platform', models.CharField(choices=[('google_calendar', 'Google Calendar'), ('microsoft_outlook', 'Microsoft Outlook')], max_length=20)),
                ('recall_id', models.CharField(max_length=255, unique=True)),
                ('recall_data', models.JSONField(default=dict)),
                ('auto_record_external_events', models.BooleanField(default=False)),
                ('auto_record_only_confirmed_events', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'calendars',
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calendar_id', models.UUIDField()),
                ('platform', models.CharField(choices=[('google_calendar', 'Google Calendar'), ('microsoft_outlook', 'Microsoft Outlook')], max_length=20)),
                ('recall_id', models.CharField(max_length=255, unique=True)),
                ('recall_data', models.JSONField(default=dict)),
                ('should_record_automatic', models.BooleanField(default=False)),
                ('should_record_manual', models.BooleanField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'calendar_events',
            },
        ),
        migrations.CreateModel(
            name='CalendarWebhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calendar_id', models.UUIDField()),
                ('event', models.CharField(max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'calendar_webhooks',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
