# Generated by Django 5.2.8 on 2025-11-29 08:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotRecording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bot_id', models.CharField(max_length=255, unique=True)),
                ('calendar_event_id', models.UUIDField(blank=True, null=True)),
                ('recall_data', models.JSONField(default=dict)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bot_recordings',
            },
        ),
        migrations.CreateModel(
            name='RecordingArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bot_recording_id', models.UUIDField()),
                ('recording_id', models.CharField(max_length=255)),
                ('artifact_type', models.CharField(choices=[('video_mixed', 'Video Mixed'), ('audio_mixed', 'Audio Mixed'), ('transcript', 'Transcript'), ('audio_separate', 'Audio Separate')], max_length=50)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('file_format', models.CharField(blank=True, max_length=50, null=True)),
                ('download_url', models.URLField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'recording_artifacts',
                'unique_together': {('bot_recording_id', 'recording_id', 'artifact_type')},
            },
        ),
    ]
