# Generated by Django 5.2.8 on 2025-12-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_botrecording_recordingartifact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordingartifact',
            name='artifact_type',
            field=models.CharField(choices=[('video_mixed', 'Video Mixed'), ('audio_mixed', 'Audio Mixed'), ('transcript', 'Transcript'), ('provider_transcript', 'Provider Transcript'), ('audio_separate', 'Audio Separate')], max_length=50),
        ),
        migrations.AlterField(
            model_name='recordingartifact',
            name='file_path',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
