# Generated by Django 5.2.8 on 2025-12-04 18:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_recordingartifact_artifact_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingTranscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calendar_event_id', models.UUIDField()),
                ('bot_id', models.CharField(max_length=255)),
                ('assemblyai_transcript_id', models.CharField(max_length=255, unique=True)),
                ('transcript_data', models.JSONField(default=dict)),
                ('transcript_text', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='processing', max_length=50)),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'meeting_transcriptions',
                'indexes': [models.Index(fields=['calendar_event_id'], name='meeting_tra_calenda_30a2a5_idx'), models.Index(fields=['bot_id'], name='meeting_tra_bot_id_08fa88_idx'), models.Index(fields=['assemblyai_transcript_id'], name='meeting_tra_assembl_f33681_idx')],
            },
        ),
    ]
