# Generated by Django 5.2.8 on 2025-12-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_meetingtranscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingtranscription',
            name='assemblyai_transcript_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='meetingtranscription',
            unique_together={('calendar_event_id', 'bot_id')},
        ),
    ]
