# Generated by Django 5.2.8 on 2025-12-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_add_backend_user_id_and_status'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='botrecording',
            new_name='bot_recordi_backend_57df2b_idx',
            old_name='bot_recordings_backend_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='calendar',
            new_name='calendars_backend_2626b4_idx',
            old_name='calendars_backend_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='calendar',
            new_name='calendars_status_fe5e59_idx',
            old_name='calendars_status_idx',
        ),
        migrations.RenameIndex(
            model_name='calendarevent',
            new_name='calendar_ev_backend_5b0777_idx',
            old_name='calendar_events_backend_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='meetingtranscription',
            new_name='meeting_tra_backend_a0f0cd_idx',
            old_name='meeting_transcriptions_backend_user_id_idx',
        ),
        migrations.AddField(
            model_name='meetingtranscription',
            name='contextual_nudges',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='meetingtranscription',
            name='impact_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='botrecording',
            index=models.Index(fields=['calendar_event_id'], name='bot_recordi_calenda_4e6eb4_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['calendar_id'], name='calendar_ev_calenda_617a96_idx'),
        ),
    ]
