# Generated by Django 5.2.8 on 2025-12-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_add_workspace_folder_to_meeting_transcription'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='botrecording',
            new_name='bot_recordi_workspa_3fc0d4_idx',
            old_name='bot_recordi_workspa_idx',
        ),
        migrations.RenameIndex(
            model_name='botrecording',
            new_name='bot_recordi_folder__1c9a45_idx',
            old_name='bot_recordi_folder__idx',
        ),
        migrations.RenameIndex(
            model_name='meetingtranscription',
            new_name='meeting_tra_workspa_59e2ef_idx',
            old_name='meeting_tra_workspa_idx',
        ),
        migrations.RenameIndex(
            model_name='meetingtranscription',
            new_name='meeting_tra_folder__dae675_idx',
            old_name='meeting_tra_folder__idx',
        ),
        migrations.AddField(
            model_name='calendar',
            name='default_folder_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='calendar',
            name='default_workspace_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
