# Generated by Django 5.2.8 on 2026-01-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_add_default_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingtranscription',
            name='notification_retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meetingtranscription',
            name='notification_sent_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='meetingtranscription',
            name='notification_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
