# Generated by Django 5.2.8 on 2026-01-01 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_add_notification_fields'),
        ('app', '0012_add_notification_model'),
    ]

    operations = [
    ]
