# Generated by Django 5.2.8 — FolderMeetingsOverview only (no Notification side-effects)

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_merge_20260101_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderMeetingsOverview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('folder_id', models.UUIDField(db_index=True)),
                ('backend_user_id', models.UUIDField(db_index=True)),
                ('source_signature', models.CharField(max_length=64)),
                ('summary', models.TextField(blank=True, default='')),
                ('action_items', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'folder_meetings_overviews',
                'unique_together': {('folder_id', 'backend_user_id')},
            },
        ),
    ]
